Repository kubewarden/deprecated-api-versions-policy, pull requests merged in 2025-03, with the labels that each got.

#106 fix!: change the tagging strategy
  .github/workflows/release.yml
  .github/workflows/test.yml
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  artifacthub-pkg.yml
  crates/policy-version-helper/.gitignore
  crates/policy-version-helper/Cargo.toml
  crates/policy-version-helper/src/cli.rs
  crates/policy-version-helper/src/main.rs
  metadata.yml
Labels: kind/bug, kind/breaking-change

#107 fix: ci check policy metadata and runs-on
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: kind/bug

#110 ci: dispatch release policy catalog workflow
  .github/workflows/release.yml
Labels: area/ci
